### ISSUE TITLE
full-icu makes binaries huge

### ISSUE THREAD

**Issue by jesec** [vercel/pkg-fetch#164]
cc: @leerob @robertsLando 
Related: nodejs/node#19214

node-v12.22.1-linux-x64
36.5 MB

node-v14.16.1-linux-x64
61.3 MB

`full-icu` is the new default. However, is it worth it?

**Comment by erossignon** [comment]
https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime

We could make it to add ICU for those who rely on it with a  --with-icu option in `pkg`.

This would emulate the technique describe in this article and embed the icu file in the exe.

**Comment by jesec** [comment]
Good idea.

**Comment by robertsLando** [comment]
Agree with @erossignon idea!

**Comment by jesec** [comment]
~We only have to handle this for Node >= 14, since older Nodes default to `small-icu` and users don't expect full-icu anyways.~

~https://github.com/nodejs/node/commit/d502b83cbdde7ecc7efb3c87503817617d7aacd1 could be useful.~

~We can use `/snapshot/.node-icu` for Unix and `C:\snapshot\.node-icu` for Windows.~

~Then, on the `pkg` side, simply fetch and place icu data to the snapshot filesystem when user specifies an option.~

~Even more amazing: with vercel/pkg#1115, the icu data inside snapshot can be compressed.~

~See also: https://github.com/nodejs/node/issues/3460#issuecomment-561279230~

This approach will not work, unfortunately. ICU data loading happens in C++ land. 

https://github.com/nodejs/node/blob/d502b83cbdde7ecc7efb3c87503817617d7aacd1/src/node.cc#L905

**Comment by jesec** [comment]
Interestingly, by the same reason I mentioned (C++ land), `NODE_ICU_DATA` will not work currently, but there is only one issue about that (vercel/pkg#539), with very limited comments. Perhaps most of our users don't really care. 

Let's do `small-icu` (#167) for now and see how things so.

**Comment by Infern1** [comment]
So I faced today that the default compile was changed to:  `--with-intl=small-icu` however when making a binary for Windows platform I got this error:
```
λ web_server.exe              
pkg/prelude/bootstrap.js:1430                                                                                                                     
      throw error;                                                                                                                                
      ^                                                                                                                                           
                                                                                                                                                  
ReferenceError: Intl is not defined                                                                                                               
    at new WebLogger (D:\snapshot\WEB_ServerTs\built\fs\WEB_Logger.js)                                                                      
    at Object.<anonymous> (D:\snapshot\WEB_ServerTs\built\fs\WEB_Logger.js)                                                                 
    at Module._compile (pkg/prelude/bootstrap.js:1503:22)                                                                                         
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)                                                                     
    at Module.load (internal/modules/cjs/loader.js:928:32)                                                                                        
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)                                                                              
    at Module.require (internal/modules/cjs/loader.js:952:19)                                                                                     
    at Module.require (pkg/prelude/bootstrap.js:1409:31)                                                                                          
    at require (internal/modules/cjs/helpers.js:88:18)                                                                                            
    at Object.<anonymous> (D:\snapshot\WEB_ServerTs\built\app.js)                                                                           
```

So I recompiled the built for Windows (x86) with the change in [build.ts](https://github.com/vercel/pkg-fetch/blob/fa6e45dbf48d07b21ba9fe47bfb136286d3c54ab/lib/build.ts#L58)

```
if (hostPlatform === 'win') {  
    args.push('--with-intl=full-icu');
  } else {
    args.push('--with-intl=small-icu');
}
```

Now my executable is working as it should no more `Intl` error.

So I'm not sure if it is specific Windows problem.

**Comment by Rafatcb** [comment]
Is there an alternative to use `full-icu` without the `--build` flag? The build process using that flag is _really_ slow, so it doesn't seem the right approach.

For now, as a workaround, I'm using `pkg` v4.5.1 again (the last version before it bumped `pkg-fetch` to v3.0.2, which contains this ICU update).

**Comment by pmb0** [comment]
@Infern1 

Please provide a command line option to `pkg` or an environment variable to control whether `small-icu` or `full-icu` is used. We use pkg to build different kinds of services. For some of them it is important to be able to format dates correctly in a certain language; for others not. 

Suggestion:

```
pkg --with-intl=small-icu (default)
pkg --with-intl=full-icu
```

**Comment by jesec** [comment]
> @jesec
> 
> Please provide a command line option to `pkg` or an environment variable to control whether `small-icu` or `full-icu` is used. We use pkg to build different kinds of services. For some of them it is important to be able to format dates correctly in a certain language; for others not.
> 
> Suggestion:
> 
> ```
> pkg --with-intl=small-icu (default)
> pkg --with-intl=full-icu
> ```

Unfortunately, ICU stuffs are loaded in C++ world, and we haven't found an effective way to intervene with that yet, as payload reading is implemented in JS world.

https://github.com/nodejs/node/blob/02de40246f261355ece1cc044e282db4db60d59b/src/node.cc#L927

At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.

**Comment by Infern1** [comment]
> 
> Unfortunately, ICU stuffs are loaded in C++ world, and we haven't found an effective way to intervene with that yet, as payload reading is implemented in JS world.
> 
> https://github.com/nodejs/node/blob/02de40246f261355ece1cc044e282db4db60d59b/src/node.cc#L927
> 
> At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.

Maybe some additional docs would certainly help.

**Comment by pmb0** [comment]
> Unfortunately, ICU stuffs are loaded in C++ world, and we haven't found an effective way to intervene with that yet, as payload reading is implemented in JS world.
> 
> https://github.com/nodejs/node/blob/02de40246f261355ece1cc044e282db4db60d59b/src/node.cc#L927
> 
> At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.

Maybe you could bundle and provide the `small-icu` binaries in https://github.com/vercel/pkg-fetch/releases/ additionally as `full-icu`, so that you can choose in `pkg` CLI which version to download?

**Comment by jesec** [comment]
> > Unfortunately, ICU stuffs are loaded in C++ world, and we haven't found an effective way to intervene with that yet, as payload reading is implemented in JS world.
> > https://github.com/nodejs/node/blob/02de40246f261355ece1cc044e282db4db60d59b/src/node.cc#L927
> > At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.
> 
> Maybe you could bundle and provide the `small-icu` binaries in https://github.com/vercel/pkg-fetch/releases/ additionally as `full-icu`, so that you can choose in `pkg` CLI which version to download?

which basically doubles my workload. :(

**Comment by Rafatcb** [comment]
> Interestingly, by the same reason I mentioned (C++ land), `NODE_ICU_DATA` will not work currently, but there is only one issue about that ([vercel/pkg#539](https://github.com/vercel/pkg/issues/539)), with very limited comments. Perhaps most of our users don't really care.

> At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.

@jesec So, just to confirm, is it possible to use `NODE_ICU_DATA` or not? Do you have any documentation about it? I've never dealt with this before so I don't really understand how the upload works and its limitations.

Another question, is it possible to use a partial ICU for specific locations? e.g. `pt-BR` and `en-US`

**Comment by TBG-FR** [comment]
As of today, looks like `pkg` isn't build with `full-icu`, causing issues (see #1731)... How could we achieve that ?

**Comment by srl295** [comment]
> Another question, is it possible to use a partial ICU for specific locations? e.g. pt-BR and en-US

Yea see docs for icutrim

**Comment by srl295** [comment]
> huge.. 36.5 MB vs 61.3 MB

Working as designed. Support for hundreds of languages takes data.

**Comment by srl295** [comment]
> > 
> 
> > Unfortunately, ICU stuffs are loaded in C++ world, and we haven't found an effective way to intervene with that yet, as payload reading is implemented in JS world.
> 
> > 
> 
> > https://github.com/nodejs/node/blob/02de40246f261355ece1cc044e282db4db60d59b/src/node.cc#L927
> 
> > 
> 
> > At this moment, we recommend users who have a need for full icu data to download ICU data to a folder, and then set `NODE_ICU_DATA` environment variable.
> 
> 
> 
> Maybe some additional docs would certainly help. 
> 
> 
> 
> 

See node's Int'l docs for full details.
