### ISSUE TITLE
Zlib of node-v14.17.2-macos-x64 is broken

### ISSUE THREAD

**Issue by umireon** [vercel/pkg-fetch#208]
[The latest node-v14.17.2-macos-x64 binary of vercel/pkg-fetch](https://github.com/vercel/pkg-fetch/releases/download/v3.2/node-v14.17.2-macos-x64) seems to be broken.

## main.js

```
var fs = require('fs');
var zlib = require('zlib');

var gzipContent = fs.readFileSync('./node-v16.6.1-darwin-x64.tar.gz');
zlib.gunzip(gzipContent, function (err, binary) {
    console.log(err)
    console.log(binary.length)
});
```

## The error

```
% ./node ./main.js
Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:188:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
/Users/umireon/git/vercelpkg-test/main.js:7
    console.log(binary.length)
                       ^

TypeError: Cannot read property 'length' of undefined
    at Gunzip.cb (/Users/umireon/git/vercelpkg-test/main.js:7:24)
    at Gunzip.zlibBufferOnError (zlib.js:144:8)
    at Gunzip.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

## Expected

```
% node ./main.js 
null
98787840
```

**Comment by jesec** [comment]
I failed to reproduce on macos-arm64: 

```sh
$ pkg -t node14-mac-arm64 main.js
> pkg@5.3.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.2-macos-arm64        [====================] 100%

$ ./main
null
98787840
```

**Comment by jesec** [comment]
This is a Node.js bug. nodejs/node#39313

A workaround has been applied, and the patched binaries will be available in the next release:

925111ba5ebf8a7d7ffdf6e45cffb202103968f7

**Comment by shaneosullivan** [comment]
I'm still running into this with a brand new project. @jesec should this no longer be an issue now, or do we as users of NextJS need to apply some workaround?

**Comment by jesec** [comment]
Please make sure that you are using the appropriate version.
